/// Curated culinary glossary, English → target language, applied BEFORE
/// ML Kit translation (see AiTranslationService._translateGuarded).
///
/// WHY: ML Kit is a small statistical translator with no food knowledge —
/// it mangles Indian culinary vocabulary ("ajwain" → gibberish, "sattu" →
/// transliteration soup). Every term in this map is replaced by a
/// placeholder before ML Kit runs and restored as the CORRECT word after,
/// so ML Kit only translates the connecting sentence around them. This is
/// the standard technique translation apps use to keep domain words exact
/// without any per-recipe AI/server call.
///
/// Rules for entries:
///  • keys are lowercase English, letters and spaces only (matched
///    case-insensitively on word boundaries, longest key first — so
///    "garlic cloves" wins over "cloves"),
///  • add BOTH singular and plural where they differ,
///  • nouns and fixed phrases only — free verbs are left to ML Kit so
///    sentence grammar stays natural.
library;

const Map<String, Map<String, String>> kFoodTermGlossary = {
  'hi': {
    // ── Units & measures ──
    'teaspoons': 'छोटे चम्मच', 'teaspoon': 'छोटा चम्मच',
    'tablespoons': 'बड़े चम्मच', 'tablespoon': 'बड़ा चम्मच',
    'cups': 'कप', 'cup': 'कप',
    'pinch': 'चुटकी',
    'bunches': 'गड्डी', 'bunch': 'गड्डी',
    'slices': 'स्लाइस', 'slice': 'स्लाइस',
    'pieces': 'टुकड़े', 'piece': 'टुकड़ा',
    'salt to taste': 'स्वादानुसार नमक',
    'to taste': 'स्वादानुसार',
    // ── Spices & seeds ──
    'ajwain': 'अजवाइन', 'carom seeds': 'अजवाइन',
    'cumin seeds': 'जीरा', 'cumin powder': 'जीरा पाउडर', 'cumin': 'जीरा',
    'mustard seeds': 'राई',
    'fenugreek seeds': 'मेथी दाना', 'fenugreek leaves': 'मेथी',
    'fenugreek': 'मेथी',
    'fennel seeds': 'सौंफ', 'fennel': 'सौंफ',
    'nigella seeds': 'कलौंजी',
    'sesame seeds': 'तिल',
    'asafoetida': 'हींग', 'hing': 'हींग',
    'turmeric powder': 'हल्दी पाउडर', 'turmeric': 'हल्दी',
    'red chili powder': 'लाल मिर्च पाउडर',
    'red chilli powder': 'लाल मिर्च पाउडर',
    'coriander powder': 'धनिया पाउडर',
    'garam masala': 'गरम मसाला',
    'chaat masala': 'चाट मसाला',
    'sambar powder': 'सांभर पाउडर',
    'pav bhaji masala': 'पाव भाजी मसाला',
    'black pepper': 'काली मिर्च',
    'black salt': 'काला नमक',
    'cardamom': 'इलायची',
    'cinnamon': 'दालचीनी',
    'bay leaf': 'तेज पत्ता', 'bay leaves': 'तेज पत्ते',
    'saffron': 'केसर',
    'dried red chilies': 'सूखी लाल मिर्च',
    'dried red chili': 'सूखी लाल मिर्च',
    'chili flakes': 'मिर्च के फ्लेक्स', 'chilli flakes': 'मिर्च के फ्लेक्स',
    'oregano': 'ऑरेगैनो',
    // ── Fresh produce & herbs ──
    'curry leaves': 'करी पत्ता',
    'coriander leaves': 'हरा धनिया', 'cilantro': 'हरा धनिया',
    'fresh coriander': 'हरा धनिया', 'coriander': 'धनिया',
    'mint leaves': 'पुदीना', 'mint': 'पुदीना',
    'ginger garlic paste': 'अदरक लहसुन का पेस्ट',
    'grated ginger': 'कद्दूकस किया अदरक', 'ginger': 'अदरक',
    'garlic cloves': 'लहसुन की कलियाँ', 'garlic': 'लहसुन',
    'cloves': 'लौंग',
    'green chilies': 'हरी मिर्च', 'green chillies': 'हरी मिर्च',
    'green chili': 'हरी मिर्च', 'green chilli': 'हरी मिर्च',
    'spring onions': 'हरा प्याज', 'spring onion': 'हरा प्याज',
    'onions': 'प्याज', 'onion': 'प्याज',
    'tomatoes': 'टमाटर', 'tomato': 'टमाटर',
    'potatoes': 'आलू', 'potato': 'आलू',
    'capsicum': 'शिमला मिर्च', 'bell pepper': 'शिमला मिर्च',
    'green peas': 'हरे मटर', 'peas': 'मटर',
    'spinach': 'पालक',
    'cabbage': 'पत्ता गोभी',
    'cauliflower': 'फूलगोभी',
    'carrots': 'गाजर', 'carrot': 'गाजर',
    'brinjal': 'बैंगन', 'eggplant': 'बैंगन',
    'bottle gourd': 'लौकी',
    'okra': 'भिंडी', 'ladyfinger': 'भिंडी',
    'cucumber': 'खीरा',
    'sweet corn': 'स्वीट कॉर्न', 'corn': 'मकई',
    'mushrooms': 'मशरूम', 'mushroom': 'मशरूम',
    'beetroot': 'चुकंदर',
    'lemon juice': 'नींबू का रस', 'lemon': 'नींबू', 'lime': 'नींबू',
    'tamarind': 'इमली',
    'jaggery': 'गुड़',
    // ── Dairy & fats ──
    'paneer': 'पनीर',
    'curd': 'दही', 'yogurt': 'दही', 'yoghurt': 'दही',
    'fresh cream': 'ताज़ी क्रीम', 'cream': 'क्रीम',
    'butter': 'मक्खन',
    'ghee': 'घी',
    'mustard oil': 'सरसों का तेल',
    'olive oil': 'जैतून का तेल',
    'oil': 'तेल',
    'milk': 'दूध',
    'cheese': 'चीज़',
    'condensed milk': 'कंडेंस्ड मिल्क',
    // ── Grains, flours & staples ──
    'wheat flour': 'गेहूं का आटा', 'whole wheat flour': 'गेहूं का आटा',
    'all purpose flour': 'मैदा', 'maida': 'मैदा',
    'gram flour': 'बेसन', 'besan': 'बेसन',
    'rice flour': 'चावल का आटा',
    'semolina': 'सूजी', 'rava': 'रवा', 'sooji': 'सूजी',
    'basmati rice': 'बासमती चावल', 'rice': 'चावल',
    'flattened rice': 'पोहा', 'poha': 'पोहा',
    'puffed rice': 'मुरमुरा', 'churmura': 'चुरमुरा', 'murmura': 'मुरमुरा',
    'sev': 'सेव',
    'vermicelli': 'सेवइयां',
    'sabudana': 'साबूदाना', 'sago': 'साबूदाना',
    'bread slices': 'ब्रेड स्लाइस', 'bread': 'ब्रेड',
    'sattu': 'सत्तू',
    'oats': 'ओट्स',
    'cornflour': 'कॉर्नफ्लोर',
    'baking powder': 'बेकिंग पाउडर',
    'baking soda': 'बेकिंग सोडा',
    'cocoa powder': 'कोको पाउडर',
    'sugar': 'चीनी',
    // ── Pulses ──
    'black chana': 'काला चना', 'chana dal': 'चना दाल',
    'chickpeas': 'छोले', 'chana': 'चना',
    'kidney beans': 'राजमा', 'rajma': 'राजमा',
    'moong dal': 'मूंग दाल', 'toor dal': 'तूर दाल', 'urad dal': 'उड़द दाल',
    'masoor dal': 'मसूर दाल',
    'lentils': 'दाल', 'dal': 'दाल',
    // ── Nuts & dry fruits ──
    'peanuts': 'मूंगफली', 'peanut': 'मूंगफली',
    'cashews': 'काजू', 'cashew': 'काजू',
    'almonds': 'बादाम', 'almond': 'बादाम',
    'raisins': 'किशमिश',
    'peanut butter': 'पीनट बटर',
    'gond katira': 'गोंद कतीरा',
    // ── Non-veg & other ──
    'chicken': 'चिकन', 'mutton': 'मटन', 'fish': 'मछली',
    'eggs': 'अंडे', 'egg': 'अंडा',
    // ── Sauces & condiments ──
    'soy sauce': 'सोया सॉस',
    'schezwan sauce': 'शेज़वान सॉस',
    'tomato ketchup': 'टमाटर केचप',
    'green chutney': 'हरी चटनी',
    'tamarind chutney': 'इमली की चटनी',
    'vinegar': 'सिरका',
    'honey': 'शहद',
    // ── Preparation phrases (fixed participles) ──
    'finely chopped': 'बारीक कटा हुआ',
    'roughly chopped': 'मोटा कटा हुआ',
    'chopped': 'कटा हुआ',
    'grated': 'कद्दूकस किया हुआ',
    'boiled': 'उबला हुआ',
    'mashed': 'मसला हुआ',
    'crushed': 'कुटा हुआ',
    'roasted': 'भुना हुआ',
    'minced': 'बारीक कटा हुआ',
    'cubed': 'टुकड़ों में कटा',
    'soaked overnight': 'रात भर भिगोया हुआ',
    'soaked': 'भिगोया हुआ',
    'pureed': 'प्यूरी किया हुआ',
    'melted': 'पिघला हुआ',
  },
  'gu': {
    // ── Units & measures ──
    'teaspoons': 'નાની ચમચી', 'teaspoon': 'નાની ચમચી',
    'tablespoons': 'મોટી ચમચી', 'tablespoon': 'મોટી ચમચી',
    'cups': 'કપ', 'cup': 'કપ',
    'pinch': 'ચપટી',
    'bunches': 'ઝૂડી', 'bunch': 'ઝૂડી',
    'slices': 'સ્લાઇસ', 'slice': 'સ્લાઇસ',
    'pieces': 'ટુકડા', 'piece': 'ટુકડો',
    'salt to taste': 'સ્વાદ મુજબ મીઠું',
    'to taste': 'સ્વાદ મુજબ',
    // ── Spices & seeds ──
    'ajwain': 'અજમો', 'carom seeds': 'અજમો',
    'cumin seeds': 'જીરું', 'cumin powder': 'જીરું પાઉડર', 'cumin': 'જીરું',
    'mustard seeds': 'રાઈ',
    'fenugreek seeds': 'મેથીના દાણા', 'fenugreek leaves': 'મેથી',
    'fenugreek': 'મેથી',
    'fennel seeds': 'વરિયાળી', 'fennel': 'વરિયાળી',
    'nigella seeds': 'કલોંજી',
    'sesame seeds': 'તલ',
    'asafoetida': 'હિંગ', 'hing': 'હિંગ',
    'turmeric powder': 'હળદર પાઉડર', 'turmeric': 'હળદર',
    'red chili powder': 'લાલ મરચું પાઉડર',
    'red chilli powder': 'લાલ મરચું પાઉડર',
    'coriander powder': 'ધાણા પાઉડર',
    'garam masala': 'ગરમ મસાલો',
    'chaat masala': 'ચાટ મસાલો',
    'black pepper': 'કાળા મરી',
    'black salt': 'સંચળ',
    'cardamom': 'એલચી',
    'cinnamon': 'તજ',
    'bay leaf': 'તમાલપત્ર', 'bay leaves': 'તમાલપત્ર',
    'saffron': 'કેસર',
    'dried red chilies': 'સૂકા લાલ મરચાં',
    'dried red chili': 'સૂકું લાલ મરચું',
    // ── Fresh produce & herbs ──
    'curry leaves': 'મીઠો લીમડો',
    'coriander leaves': 'કોથમીર', 'cilantro': 'કોથમીર',
    'fresh coriander': 'કોથમીર', 'coriander': 'ધાણા',
    'mint leaves': 'ફુદીનો', 'mint': 'ફુદીનો',
    'ginger garlic paste': 'આદુ લસણની પેસ્ટ',
    'grated ginger': 'છીણેલું આદુ', 'ginger': 'આદુ',
    'garlic cloves': 'લસણની કળીઓ', 'garlic': 'લસણ',
    'cloves': 'લવિંગ',
    'green chilies': 'લીલાં મરચાં', 'green chillies': 'લીલાં મરચાં',
    'green chili': 'લીલું મરચું', 'green chilli': 'લીલું મરચું',
    'onions': 'ડુંગળી', 'onion': 'ડુંગળી',
    'tomatoes': 'ટામેટાં', 'tomato': 'ટામેટું',
    'potatoes': 'બટાકા', 'potato': 'બટાકું',
    'capsicum': 'કેપ્સીકમ', 'bell pepper': 'કેપ્સીકમ',
    'green peas': 'લીલા વટાણા', 'peas': 'વટાણા',
    'spinach': 'પાલક',
    'cabbage': 'કોબીજ',
    'cauliflower': 'ફ્લાવર',
    'carrots': 'ગાજર', 'carrot': 'ગાજર',
    'brinjal': 'રીંગણ', 'eggplant': 'રીંગણ',
    'bottle gourd': 'દૂધી',
    'okra': 'ભીંડા', 'ladyfinger': 'ભીંડા',
    'lemon juice': 'લીંબુનો રસ', 'lemon': 'લીંબુ',
    'tamarind': 'આમલી',
    'jaggery': 'ગોળ',
    // ── Dairy & fats ──
    'paneer': 'પનીર',
    'curd': 'દહીં', 'yogurt': 'દહીં', 'yoghurt': 'દહીં',
    'fresh cream': 'તાજી ક્રીમ', 'cream': 'ક્રીમ',
    'butter': 'માખણ',
    'ghee': 'ઘી',
    'mustard oil': 'સરસવનું તેલ',
    'oil': 'તેલ',
    'milk': 'દૂધ',
    'cheese': 'ચીઝ',
    // ── Grains, flours & staples ──
    'wheat flour': 'ઘઉંનો લોટ', 'whole wheat flour': 'ઘઉંનો લોટ',
    'all purpose flour': 'મેંદો', 'maida': 'મેંદો',
    'gram flour': 'બેસન', 'besan': 'બેસન',
    'rice flour': 'ચોખાનો લોટ',
    'semolina': 'સોજી', 'rava': 'રવો', 'sooji': 'સોજી',
    'basmati rice': 'બાસમતી ચોખા', 'rice': 'ચોખા',
    'flattened rice': 'પૌંઆ', 'poha': 'પૌંઆ',
    'puffed rice': 'મમરા', 'churmura': 'મમરા', 'murmura': 'મમરા',
    'sev': 'સેવ',
    'sabudana': 'સાબુદાણા',
    'bread slices': 'બ્રેડ સ્લાઇસ', 'bread': 'બ્રેડ',
    'sattu': 'સત્તુ',
    'sugar': 'ખાંડ',
    // ── Pulses ──
    'black chana': 'કાળા ચણા', 'chana dal': 'ચણાની દાળ',
    'chickpeas': 'છોલે', 'chana': 'ચણા',
    'kidney beans': 'રાજમા', 'rajma': 'રાજમા',
    'moong dal': 'મગની દાળ', 'toor dal': 'તુવેરની દાળ',
    'urad dal': 'અડદની દાળ',
    'lentils': 'દાળ', 'dal': 'દાળ',
    // ── Nuts, non-veg, condiments ──
    'peanuts': 'સિંગદાણા', 'peanut': 'સિંગદાણા',
    'cashews': 'કાજુ', 'almonds': 'બદામ', 'raisins': 'કિસમિસ',
    'chicken': 'ચિકન', 'eggs': 'ઈંડાં', 'egg': 'ઈંડું',
    'green chutney': 'લીલી ચટણી',
    'tamarind chutney': 'આમલીની ચટણી',
    'honey': 'મધ',
    // ── Preparation phrases ──
    'finely chopped': 'ઝીણું સમારેલું',
    'chopped': 'સમારેલું',
    'grated': 'છીણેલું',
    'boiled': 'બાફેલું',
    'mashed': 'છૂંદેલું',
    'crushed': 'ખાંડેલું',
    'roasted': 'શેકેલું',
    'soaked overnight': 'આખી રાત પલાળેલું',
    'soaked': 'પલાળેલું',
    'pureed': 'પ્યુરી કરેલું',
    'melted': 'ઓગાળેલું',
  },
};
